# Generated by Django 4.1.1 on 2022-09-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_produto_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
    ]
